language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools

#    # The BuildTools version used by your project
#    - build-tools-28.0.3
#
#    # The SDK version used to compile your project
#    - android-28

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
- "./gradlew clean build detekt install"

deploy:
  provider: releases
  file:
    - /
  skip_cleanup: true
  on:
    repo: 10bis/CompactCreditInput
    tags: true